# This file was generated by GoReleaser. DO NOT EDIT.
cask "sitehost-tui" do
  version "0.1.5"

  on_macos do
    on_intel do
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_darwin_amd64.tar.gz"
      sha256 "02bd4fec3c06d31c14609778b8bf990e2d17fa92c433db4281bb72576ac578d4"
    end
    on_arm do
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_darwin_arm64.tar.gz"
      sha256 "3d4323829fdc7cfa1d53b1327e5baac5c0128232adce0cab14e73e5d25941739"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_linux_amd64.tar.gz"
      sha256 "01889ba8e13a30f30a0fee97d6095a7fe01704c48a161e0c37efb3172761b2f6"
    end
    on_arm do
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_linux_arm64.tar.gz"
      sha256 "c2049f161decf5d0125b61d000859311f1aeef1d17f113c80177d85043f17433"
    end
  end

  name "sitehost-tui"
  desc "Terminal UI for managing SiteHost cloud services"
  homepage "https://github.com/csalwin/Sithost-tui-go-port"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sitehost-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sitehost-tui"]
    end
  end

  # No zap stanza required

end
