# This file was generated by GoReleaser. DO NOT EDIT.
cask "sitehost-tui" do
  version "0.1.7"

  on_macos do
    on_intel do
      sha256 "4bb6bdf0358f6fb977e9933b942003ffe3a1006bc9f065b77fec4920898f0bc4"
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f194042c4caf67e19685e08b990269a50b8270f5e04fdaa28d12ba64b10acc8f"
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c311a33b78a2f4cb7dc02f6af26d2f7e7d74d2e0a95f99ceb63c2c8a2a97204f"
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a9677d2ba27291ec996f40ec399f803b5acf03ff071969c6afdf685af6613a8"
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sitehost-tui"
  desc "Terminal UI for managing SiteHost cloud services"
  homepage "https://github.com/csalwin/Sithost-tui-go-port"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sitehost-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sitehost-tui"]
    end
  end

  # No zap stanza required

end
