# This file was generated by GoReleaser. DO NOT EDIT.
cask "sitehost-tui" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "1667eb958e349d450da74605a999977e50f24a8cfec6124fa8ba383af5ecc342"
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "71048384db3c22c90489f877bbc15468251f67ea82641f3a7fa6d4922708608f"
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "91155204f04684a9e32c8732adf1711d5519a9ecbebec3b398becb8951444120"
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a49b665a836123b71324b28c4fbd8c92b1b00cc2fbd2ea8a68b5c2e3a0a08b68"
      url "https://github.com/csalwin/homebrew-tap/releases/download/v#{version}/sitehost-tui_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sitehost-tui"
  desc "Terminal UI for managing SiteHost cloud services"
  homepage "https://github.com/csalwin/Sithost-tui-go-port"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sitehost-tui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/sitehost-tui"]
    end
  end

  # No zap stanza required

end
