# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitehostTui < Formula
  desc "Terminal UI for managing SiteHost cloud services"
  homepage "https://github.com/chrisAlwinYS/Sithost-tui-go-port"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/csalwin/Sithost-tui-go-port/releases/download/v0.1.3/sitehost-tui_0.1.3_darwin_amd64.tar.gz"
      sha256 "4acc7d6aba4c45045e6eff3043d2ca05a5aba31737a4c1e85c6a1aac679d1583"

      define_method(:install) do
        bin.install "sitehost-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/csalwin/Sithost-tui-go-port/releases/download/v0.1.3/sitehost-tui_0.1.3_darwin_arm64.tar.gz"
      sha256 "7fddf990ffe47aeb03d1b1274aa2f055c358e17b18b8c220b0fa06e79ffb5913"

      define_method(:install) do
        bin.install "sitehost-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/csalwin/Sithost-tui-go-port/releases/download/v0.1.3/sitehost-tui_0.1.3_linux_amd64.tar.gz"
      sha256 "657275b7536d0b196f69c8e89921d6aad0bbc5e83cfe2d76061815dcab7336ad"
      define_method(:install) do
        bin.install "sitehost-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/csalwin/Sithost-tui-go-port/releases/download/v0.1.3/sitehost-tui_0.1.3_linux_arm64.tar.gz"
      sha256 "a5c431fc7d07d3539ce66fd270ad2c8574b727711e4781cd74957aa7139a3dc9"
      define_method(:install) do
        bin.install "sitehost-tui"
      end
    end
  end

  test do
    system "#{bin}/sitehost-tui --version"
  end
end
